import {Heap} from './data_structures/Heap.js'

var h = new Heap ('max')

h.insert (1)
h.insert (2)
h.insert (3)
h.insert (4)
h.insert (5)
h.insert (6)
console.log (h.getTop ())
console.log (h.show ())
console.log (h.getTop ())
console.log (h.show ())
console.log (h.getTop ())
console.log (h.show ())
console.log (h.getTop ())
console.log (h.show ())
console.log (h.getTop ())
console.log (h.show ())
console.log (h.getTop ())
console.log (h.show ())
console.log (h.getTop ())
console.log (h.show ())
